[project]
name = "grate"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "matplotlib",
    "xarray",
    "netcdf4",
    "h5netcdf",
    "mat73",
    "torch",
    "gpytorch",
    "geopandas",
    "pyproj",
    "rioxarray>=0.19.0",
    "dvc[gdrive]>=3.66.1",
    "scikit-gstat>=1.0.23",
    "palettable>=3.3.3",
]
